// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Header → Links*
 */
export interface HeaderDocumentDataLinksItem {
  /**
   * Emoji field in *Header → Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 🛒
   * - **API ID Path**: header.links[].emoji
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  emoji: prismic.KeyTextField;

  /**
   * Texto field in *Header → Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Comprar
   * - **API ID Path**: header.links[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Path field in *Header → Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: /
   * - **API ID Path**: header.links[].path
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  path: prismic.KeyTextField;

  /**
   * Onde abrir o link field in *Header → Links*
   *
   * - **Field Type**: Select
   * - **Placeholder**: _self
   * - **Default Value**: _self
   * - **API ID Path**: header.links[].target
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  target: prismic.SelectField<'_self' | '_blank', 'filled'>;

  /**
   * Sublinks (formato JSON) field in *Header → Links*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: [{ emoji: string; title: string; subtitle: string; path: string; target: '_self' | '_blank' }]
   * - **API ID Path**: header.links[].sublinks
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sublinks: prismic.RichTextField;
}

/**
 * Content for Header documents
 */
interface HeaderDocumentData {
  /**
   * Nome da Empresa field in *Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Cozinha Alternativa
   * - **API ID Path**: header.company_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  company_name: prismic.KeyTextField;

  /**
   * Logo field in *Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.company_brand
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  company_brand: prismic.ImageField<never>;

  /**
   * Links field in *Header*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: header.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<HeaderDocumentDataLinksItem>>;
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<HeaderDocumentData>,
  'header',
  Lang
>;

type LinkDocumentDataSlicesSlice = never;

/**
 * Content for Link documents
 */
interface LinkDocumentData {
  /**
   * Emoji field in *Link*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 🛒
   * - **API ID Path**: link.emoji
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  emoji: prismic.KeyTextField;

  /**
   * Título field in *Link*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Comprar
   * - **API ID Path**: link.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Subtítulo field in *Link*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Preparadas na nossa cozinha e entregues à tua casa.
   * - **API ID Path**: link.subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Caminho field in *Link*
   *
   * - **Field Type**: Text
   * - **Placeholder**: /
   * - **API ID Path**: link.path
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  path: prismic.KeyTextField;

  /**
   * Onde abrir o link field in *Link*
   *
   * - **Field Type**: Select
   * - **Placeholder**: _self
   * - **Default Value**: _self
   * - **API ID Path**: link.target
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  target: prismic.SelectField<'_self' | '_blank', 'filled'>;

  /**
   * `slices` field in *Link*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: link.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<LinkDocumentDataSlicesSlice>;
}

/**
 * Link document from Prismic
 *
 * - **API ID**: `link`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LinkDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<LinkDocumentData>,
  'link',
  Lang
>;

export type AllDocumentTypes = HeaderDocument | LinkDocument;

declare module '@prismicio/client' {
  interface CreateClient {
    (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (repositoryNameOrEndpoint: string, options: prismic.WriteClientConfig): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HeaderDocument,
      HeaderDocumentData,
      HeaderDocumentDataLinksItem,
      LinkDocument,
      LinkDocumentData,
      LinkDocumentDataSlicesSlice,
      AllDocumentTypes,
    };
  }
}
